name: CI

on:
  push:
    branches:    
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    # Standard drop-in approach that should work for most people.
    - uses: ammaraskar/sphinx-action@0.4
      with:
        pre-build-command: "pip install recommonmark"
        docs-folder: "."

    # Great extra actions to compose with:
    # Create an artifact of the html output.
    - uses: actions/upload-artifact@v1
      with:
        name: DocumentationHTML
        path: ./_build/html/
        
    - name: Add .nojekyll file
      run: sudo touch ./_build/html/.nojekyll
                
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v1.4.1
      with:
        # Create incremental commit instead of doing push force
        keep_history: false # optional, default is false
        # Allow an empty commit to be created
        allow_empty_commit: true # optional, default is true
        # Build directory to deploy
        build_dir: ./_build/html
        # Commit author's name
        committer_name: "GitHub Action" # optional
        # Commit author's email
        committer_email: "action@github.com" # optional
        # Commit message
        commit_message: "Update documentation"# optional
        # Write the given domain name to the CNAME file
      env:
        GITHUB_PAT: ${{ secrets.PAT }}
